# Generated by Django 4.2.30 on 2026-06-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('completed_topics', models.JSONField(blank=True, default=list)),
                ('project_codebase', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
