import React from 'react';

export const topic40Content = {
  description: "Packaging your entire backend into a single executable.",
  difficulty: "Advanced" as const,
  paragraphs: [
    <p key="1">
      When you deploy a React or Vue frontend, you run a bundler like Webpack or Vite. It crawls all of your imports and squashes your entire codebase down into a single optimized JavaScript file that the browser can download quickly.
    </p>,
    <p key="2">
      Historically, backend Node.js code was never bundled. You would just ZIP up your 1,000 source files and your massive <code>node_modules</code> folder, copy it to the server, and run <code>node index.js</code>. However, copying 50,000 tiny files in <code>node_modules</code> to a cloud server or a Docker container takes a huge amount of time and disk space.
    </p>,
    <p key="3">
      Modern Node.js deployment heavily relies on backend bundling! Tools like <strong>esbuild</strong> or <strong>Webpack</strong> can crawl your backend code and tree-shake your <code>node_modules</code>, outputting a single, ultra-fast <code>server.bundle.js</code> file that requires exactly zero dependencies to run in production.
    </p>
  ],
  basicExample: `// 1. Install esbuild
// npm install esbuild --save-dev

// 2. Add this script to your package.json:
// "build": "esbuild src/index.js --bundle --platform=node --target=node18 --outfile=dist/server.js"

// 3. Run the build
// npm run build

// esbuild will instantly crawl your code, follow every require() and import,
// strip out TypeScript/JSX, and generate a single dist/server.js file.

// 4. In production, you only need to run:
// node dist/server.js
// (You do not need to upload your node_modules folder!)`,
  advancedTitle: "Real-World: Creating Single Executable Applications (SEA)",
  advancedParagraphs: [
    <p key="1">
      What if you want to give your CLI tool to a friend who doesn't even have Node.js installed?
    </p>,
    <p key="2">
      Node.js now officially supports building <strong>Single Executable Applications (SEA)</strong>. You bundle your code into a single file, and then you literally inject that JavaScript file directly into the <code>node.exe</code> binary itself using a tool like Postman's <code>pkg</code> or the native Node.js SEA feature!
    </p>,
    <p key="3">
      The result is a standalone <code>my-app.exe</code> (or <code>my-app</code> on Mac/Linux) that contains both your code and the V8 engine. Anyone can run it instantly without installing Node.js!
    </p>
  ],
  advancedExample: `// The theoretical process of building a Native Executable in modern Node.js

// 1. Bundle your code into a single file
// esbuild src/index.js --bundle --platform=node --outfile=dist/bundle.js

// 2. Create a configuration file (sea-config.json)
/*
{
  "main": "dist/bundle.js",
  "output": "sea-prep.blob"
}
*/

// 3. Generate the blob
// node --experimental-sea-config sea-config.json

// 4. Inject the blob into a copy of the Node.js executable
// This requires OS-specific injection tools like 'postject'

// You now have a 50MB standalone executable!`,
  miniProject: {
    title: "The Zero-Dependency Docker Container",
    description: (
      <>
        <p>
          <strong>Goal:</strong> Optimize the deployment of an Express API by bundling it and creating a hyper-minimal Docker image.
        </p>
        <p>
          Write a standard Express app with several nested routes and utility files. Install <code>esbuild</code>. Write a build script that bundles everything into <code>out.js</code>. Then, write a <code>Dockerfile</code> that uses the <code>node:18-alpine</code> base image. Instead of copying <code>package.json</code> and running <code>npm install</code> in the container (which results in a 500MB+ image), ONLY copy <code>out.js</code> and run it directly! 
        </p>
      </>
    ),
    code: `// The highly-optimized Dockerfile

# Start from the tiny Alpine Linux version of Node
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# We DO NOT copy package.json or node_modules!
# We ONLY copy the bundled output file generated by esbuild on our local machine
COPY dist/out.js ./

# Expose the port
EXPOSE 3000

# Run the single file directly!
CMD ["node", "out.js"]

# The resulting Docker image will be drastically smaller and 
# will start up much faster in AWS/Google Cloud!`
  },
  quiz: {
    title: "Module VII: Advanced System Architecture Quiz",
    questions: [
      {
        question: "What core design pattern powers almost every module in Node.js?",
        options: ["The MVC Pattern", "The Singleton Pattern", "The EventEmitter Pattern", "The Factory Pattern"],
        correctAnswerIndex: 2,
        explanation: "Node.js relies heavily on the Observer pattern via the EventEmitter class, allowing decoupled systems to react to asynchronous events."
      },
      {
        question: "What is the primary cause of a Memory Leak in a Node.js server?",
        options: [
          "Using too many Promises",
          "Accidentally keeping references to objects (like storing them in a global array forever), preventing the Garbage Collector from freeing them",
          "Writing infinite loops",
          "Using the 'fs' module"
        ],
        correctAnswerIndex: 1,
        explanation: "V8's Garbage Collector can only clean up memory if an object is completely unreachable. If you store user sessions in an array and never delete them, they will stay in RAM until the server crashes."
      },
      {
        question: "What does the `async_hooks` module allow you to do?",
        options: [
          "Create faster HTTP servers",
          "Track the exact lineage and execution context of an asynchronous operation across the Event Loop",
          "Write React hooks in Node.js",
          "Automatically fix memory leaks"
        ],
        correctAnswerIndex: 1,
        explanation: "async_hooks (and its high-level wrapper AsyncLocalStorage) allows you to attach context (like a Request ID) to a specific execution thread, even as it bounces around the asynchronous Event Loop."
      },
      {
        question: "Why would you bundle a Node.js backend using esbuild before deploying to production?",
        options: [
          "To make the code readable",
          "To convert it to Python",
          "To squash thousands of files in node_modules into a single, highly-optimized executable file, drastically reducing deployment time and Docker image size",
          "You should never bundle backend code"
        ],
        correctAnswerIndex: 2,
        explanation: "Bundling the backend removes the massive overhead of uploading a 50,000-file node_modules directory, allowing for blazing-fast container startups."
      }
    ]
  }
};
